### PR TITLE
Catch Fatal errors - should fix #89

### LINKED ISSUE #89: UndefinedBehaviorError uncaught; freeze SBT
Errors like this in tests:

```
scala.scalajs.runtime.UndefinedBehaviorError: An undefined behavior was detected: undefined is not an instance of java.lang.Integer
```

aren't caught by μtest, and so they freeze SBT without any visual output.

It's probably because they're defined as fatal errors. You might be using `Try` or have a `case NonFatal(t) =>` somewhere. It should change to just a `try ??? catch {case  t: Throwable => ??? }`.

### PR DESCRIPTION
**Pull request by tekacs**
I'll rely on CI to verify whether this is consistent with everything else in uTest.

(I'm on the road, looking through old issues on a tablet)

### CODE REVIEW

**Comment by japgolly** [comment]
Is this the same as #92?

**Comment by tekacs** [comment]
Looks like it - I also forgot to come back and fix the patch when I was at a desktop - I'll do it in a sec. :P

**Comment by tekacs** [comment]
Okay I take that back - the tests seem to fail on master too, so the build failure doesn't appear to be my fault. 😝

**Comment by japgolly** [comment]
This should be resolved in 0.4.5.

**Pull request closed without merging**
