### PR TITLE
Handle Fatal exceptions so SBT doesn't freeze

### PR DESCRIPTION
**Pull request by japgolly**

### CODE REVIEW

**Comment by japgolly** [comment]
Rebased.

@lihaoyi @larsrh Please merge this. It's been sitting around for nearly a year with no comment.

**Comment by larsrh** [comment]
Sorry, I can't merge pull requests.

**Comment by lihaoyi** [comment]
sorry i havent been responsive

ill look at this now that you've pinged it again but give me some time.
Have been on the road since ScalaExchange and just got home :p

If i still don't do it, keep pinging this issue and it'll keep appearing in
my inbox until I do it

**Comment by lihaoyi** [comment]
0.4.5 is on the way to maven central; may the force be with them

**Comment by japgolly** [comment]
Woah, awesome @lihaoyi and thanks! Now that you've let me know your protocol, from now on I'll bug you every 2 weeks or so. :) Should be a good balance between reminding you and not annoying you. 😀 

@larsrh No worries & thanks anyway

**Pull request merged**
