### PR TITLE
Before after all support

### PR DESCRIPTION
**Pull request by d1egoaz**

### CODE REVIEW

**Comment by lihaoyi** [comment]
What's the different between putting stuff in BeforeAll and just putting
that code in the object body? If it's the same, we could do without a
BeforeAll hook and only have the AfterAll hook

**Comment by diego-alvarez-hs** [comment]
:) old habits, I was thinking in having some symmetric method to the `utestAfterAll` but I agree, let's keep it simple as it isn't necessary

**Comment by lihaoyi** [comment]
Looks good to me

**Comment by lihaoyi** [comment]
@diego-alvarez-hs one thing that we should do before publishing this is make sure that failures in the `utestBeforeEach`, `utestAfterEach`, `utestAfterAll` and in the initialization of the `TestSuite` body are handled in a reasonable way. Do you know what the current behavior is, if one of those things fails?

**Comment by d1egoaz** [comment]
Good question! I usually don't put throwable code on those places; I'll
test it and I'll get back to you with my findings

**Comment by d1egoaz** [comment]
This is what I found:

# Exceptions handling by scalatest:

## beforeEach, afterEach, beforeAll, afterAll
It fails the entire test suite
```text
[info] Exception encountered when attempting to run a suite with class name: com.xxxx.Test *** ABORTED *** (571 milliseconds)
[info]   java.lang.Exception: test
[info]   at
```

## class body:
Test suite is not created
```text
[info] Exception encountered when attempting to run a suite with class name: org.scalatest.DeferredAbortedSuite *** ABORTED *** (38 milliseconds)
[info]   java.lang.Exception: test
```

## Individual test exception:
Fails specific test
```text
[info] Some test suite
[info] - should foo and bar (429 milliseconds)
[info] - should xxxx *** FAILED *** (60 milliseconds)
[info]   java.lang.Exception: test
[info]   at
```

I was thinking we can do better for the `beforeEach, afterEach` cases and report that on the affected tests rather that fail the entire suite
something like this in the executor: https://github.com/d1egoaz/utest/blob/9d8943052ed6849c7227999613f26d43912ca2d3/utest/shared/src/main/scala/utest/framework/Executor.scala
```scala
  def utestWrap(path: Seq[String], runBody: => concurrent.Future[Any])
               (implicit ec: concurrent.ExecutionContext): concurrent.Future[Any] = {
    Future { utestBeforeEach() }
      .flatMap(_ => runBody)
      .andThen {
      case _ => utestAfterEach() // we don't care about exceptions here http://www.scala-lang.org/api/2.12.3/scala/concurrent/Future.html#andThen[U](pf:PartialFunction[scala.util.Try[T],U])(implicitexecutor:scala.concurrent.ExecutionContext):scala.concurrent.Future[T]
    }
}
```

**Comment by lihaoyi** [comment]
Yeah we should make failures in `beforeEach` and `afterEach` fail that individual test.

**Pull request merged**
