### PR TITLE
fix build on JDK 11 by working around scala/bug#11125

### PR DESCRIPTION
**Pull request by SethTisue**
this is for the benefit of the Scala community build

### CODE REVIEW

**Comment by SethTisue** [comment]
hmm... all the jobs are green except one, and it seems implausible that the failure is related to this change.

I don't have the necessary rights to just hit "rebuild" on that one job and see if the failure might be transient?

**Comment by japgolly** [comment]
I was thinking the same and I've hit rebuild on that one job either 2 or 3 times already (don't remember exactly which) and it's consistently come back red. :(

**Comment by japgolly** [comment]
More data is nearly always a good thing. I'll kick it off again and let's see what happens. You never know

**Comment by japgolly** [comment]
Travis says nein.

**Comment by SethTisue** [comment]
sigh. I don't know what to think

**Comment by sjrd** [comment]
Maybe `master` doesn't reliably build?

**Comment by SethTisue** [comment]
oh, ha, now that I take a closer look...

it isn't the code change, it's the comment I added (!)

the added line changes the line numbers in the expected outputs. The test is self-referential, it contains line numbers referencing its own source code — I wasn't expecting that. (And after all that Douglas Hofstadter I've read, too.)

Fix force-pushed. Travis is green now.

**Pull request merged**
