### PR TITLE
Addresses #41 - output verbosity - by hiding progress logging by default, enabled by a --progress flag

### PR DESCRIPTION
**Pull request by benhutchison**

### CODE REVIEW

**Comment by benhutchison** [comment]
Bump!

**Comment by benhutchison** [comment]
uTest has a lengthy section [Why uTest](https://github.com/lihaoyi/utest#why-utest) on its _technical_ strengths vs the alternatives. Its a strong & convincing argument, which is why Im using it.

Here's my counterpoint: Why not uTest? 

_The project governance model_. Or lack thereof. If you adopt uTest and want input/contribution into the tool, its very unclear if/how users can do that, other than "take what you're given, get forked if you're not happy".

I've got an issue that bothers me: #41. Ive tried to engage constructively to get it addressed, first with detailed comments backed by real-world examples, and then with a PR. All in all Ive burned about 8 hours, and ~15 months elapsed, since opening the issue, and Ive got almost nowhere on resolving it.

**Comment by lihaoyi** [comment]
Why not fork it?

**Comment by benhutchison** [comment]
Why not fork it? I just want a simple, reliable & usable testing tool that's scala.js compatible. I have no aspiration to maintain my own testing library.

**Comment by lihaoyi** [comment]
> I have no aspiration to maintain my own testing library.

Believe me, neither do I...

**Comment by lihaoyi** [comment]
Honestly the project could use some love. I literally haven't touched it for a year, and there's a backlog of things to fix, this one being one of them. I'll get back to fixing it up at some point.

**Comment by lihaoyi** [comment]
https://github.com/lihaoyi/utest/issues/85

**Comment by lihaoyi** [comment]
Fixed in the WIP `test` branch targeting 0.4.0

**Pull request closed without merging**
