### PR TITLE
Update Scala Native to 0.4.0

### PR DESCRIPTION
**Pull request by lolgab**
Depends on mill update: https://github.com/lihaoyi/mill/pull/1108

### CODE REVIEW

**Comment by sideeffffect** [comment]
mill has been published :tada: 
https://github.com/lihaoyi/mill/actions/runs/497134711

**Comment by lihaoyi** [comment]
@lolgab happy to merge/publish once this is green

**Comment by lolgab** [comment]
@lihaoyi Ready for review 😊

**Comment by lihaoyi** [comment]
@lolgab looks good, once you get CI green I'll merge and publish a new version

**Pull request merged**
