### PR TITLE
Added support for Scala Native 0.4.0-M2.

### PR DESCRIPTION
**Pull request by lolgab**
Added support for crosscompilation between Scala Native 0.3.9 and 0.4.0-M1. Waiting for Scala Native 0.4.0-M1 to be on Sonatype.

### CODE REVIEW

**Comment by lolgab** [comment]
@lihaoyi Can you trigger a Travis Rebuild now that Scala Native 0.4.0-M1 is out? Thank you.

**Comment by sjrd** [comment]
Done.

**Comment by lolgab** [comment]
Thank you @sjrd , I overlooked the fact that the release is not ready yet on Maven.. So, Travis build still fails.

**Comment by lolgab** [comment]
Now everything should be in place, I'm ready for review.

**Comment by sjrd** [comment]
There are conflicts with the base branch. Could you rebase first, please?

**Comment by lolgab** [comment]
Yes I'm going to do it right now. Another thing, before knowing that milestone releases are not binary compatible with each other I updated Scala.js from 1.0.0-M1 to the latest 1.0.0-M7. Now that I know they are two completely different artifacts, I understand that it is not necessarily good to update. Should I revert the change?

**Comment by lolgab** [comment]
I merged the commits in a commit with a more meaningful comment.

**Comment by sjrd** [comment]
There's absolutely no reason whatsoever to keep supporting old milestones of Scala.js 1.x. Upgrading to M7 is good.

**Comment by lolgab** [comment]
Perfect, then I'm asking on Scala Native gitter for someone to review 👌.

**Comment by densh** [comment]
LGTM! 👍

**Pull request merged**
