### PR TITLE
Add support for Scala.js 1.0.0-RC1.

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

**Comment by lihaoyi** [comment]
looks good to me. @sjrd would you like me to publish a 0.7.2 artifact containing this change?

**Comment by sjrd** [comment]
> would you like me to publish a 0.7.2 artifact containing this change?

That would be nice, if you can spare some time for it, yes. :)

**Comment by lihaoyi** [comment]
0.7.2 should be on its way to maven central

**Comment by sjrd** [comment]
Thanks @lihaoyi! 🎉

**Pull request merged**
