### PR TITLE
prepare Scala 2.13.0-M4. use collection.Seq instead of scala.Seq

### PR DESCRIPTION
**Pull request by xuwei-k**
https://github.com/scala/scala/blob/de77496cf0dc282ec0b36c74459cd6bfcd45e246/src/library/scala/package.scala#L52

### CODE REVIEW

**Comment by olafurpg** [comment]
The CI failure should be fixed if you rebase on master thanks to #157

**Comment by xuwei-k** [comment]
rebased

**Comment by SethTisue** [comment]
ping @lihaoyi

**Comment by SethTisue** [comment]
@xuwei-k I'm using this branch in the Scala 2.13 community build, but I'm still seeing Seq/Buffer compile errors at https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/1251/consoleFull ...?

**Comment by lihaoyi** [comment]
sure i guess

**Pull request merged**
