### PR TITLE
cross compile with Scala 2.12.x

### PR DESCRIPTION
**Pull request by larsrh**
Includes dependency updates for macros and Akka.

### CODE REVIEW

**Comment by larsrh** [comment]
Version `0.4.4` is released, based on c482901.

```scala
"com.lihaoyi" %% "utest" % "0.4.4"
```

**Comment by MasseGuillaume** [comment]
haha ops I fail again at open source: https://github.com/lihaoyi/utest/pull/102

**Comment by larsrh** [comment]
@MasseGuillaume No worries, that happened to me too :smile:

**Comment by MasseGuillaume** [comment]
@larsrh I rebased my changes to your PR ;-)

**Comment by zoosky** [comment]
+1

**Comment by larsrh** [comment]
2.12 release is blocking on Akka.

**Comment by lihaoyi** [comment]
If @larsrh, or anyone else has time, the only reason we depend on akka is for a scheduler in our own test code:

https://github.com/lihaoyi/utest/blob/927cebc46985e06f4f48e81de2c08097a1b4b1ad/utest/jvm/src/test/scala/utest/Scheduler.scala

Shouldn't be hard to remove it and replace it with some builtin JVM version, which would open the door to publishing. This is probably a good thing to do anyway from a dependency hygiene point of view. Otherwise we'll have to waiting for akka to get their 2.12 version first, which may be a few more days but not the end of the world

**Comment by larsrh** [comment]
How about a plain old [`ScheduledThreadPoolExecutor`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ScheduledThreadPoolExecutor.html)?

**Comment by lihaoyi** [comment]
yeah that should work

**Comment by larsrh** [comment]
Let me try this out ...

**Comment by larsrh** [comment]
@lihaoyi That was straightforward; see e7ccfbf.

**Comment by larsrh** [comment]
Build is green. May I proceed with the release?

**Comment by lihaoyi** [comment]
Let's do it. Thanks @larsrh!

**Comment by larsrh** [comment]
Given that I only changed some test dependencies, I took the liberty of releasing with the same version.

@lihaoyi, I created tags for the `0.4.4` release which you can pull from my fork: https://github.com/larsrh/utest

**Pull request merged**
