### PR TITLE
Upgrade Scala and Scala.JS versions

### PR DESCRIPTION
**Pull request by japgolly**

### CODE REVIEW

**Comment by japgolly** [comment]
Can somebody please merge and publish this. I'd really like to test my projects against Scala.JS 1.0.0-RC2 before it goes final :)

**Comment by lihaoyi** [comment]
looks good to me. I’ll merge and publish when back at a computer

**Comment by japgolly** [comment]
awesome, thanks @lihaoyi

**Comment by lihaoyi** [comment]
@japgolly I just ran `publishAll` on tag 0.7.3, should be on its way to maven central.

@anatoliykmetyuk I think I saw Dotty versions go out in that `publishAll` as well:

```text
Uploading com/lihaoyi/utest_0.21/0.7.3/utest_0.21-0.7.3.jar
Uploading com/lihaoyi/utest_0.21/0.7.3/utest_0.21-0.7.3.jar.md5
Uploading com/lihaoyi/utest_0.21/0.7.3/utest_0.21-0.7.3.jar.sha1
Uploading com/lihaoyi/utest_0.21/0.7.3/utest_0.21-0.7.3-sources.jar
Uploading com/lihaoyi/utest_0.21/0.7.3/utest_0.21-0.7.3-sources.jar.md5
Uploading com/lihaoyi/utest_0.21/0.7.3/utest_0.21-0.7.3-sources.jar.sha1
Uploading com/lihaoyi/utest_0.21/0.7.3/utest_0.21-0.7.3-javadoc.jar
Uploading com/lihaoyi/utest_0.21/0.7.3/utest_0.21-0.7.3-javadoc.jar.md5
Uploading com/lihaoyi/utest_0.21/0.7.3/utest_0.21-0.7.3-javadoc.jar.sha1
Uploading com/lihaoyi/utest_0.21/0.7.3/utest_0.21-0.7.3.pom
Uploading com/lihaoyi/utest_0.21/0.7.3/utest_0.21-0.7.3.pom.md5
Uploading com/lihaoyi/utest_0.21/0.7.3/utest_0.21-0.7.3.pom.sha1
Uploading com/lihaoyi/utest_0.21/0.7.3/utest_0.21-0.7.3.jar.asc
Uploading com/lihaoyi/utest_0.21/0.7.3/utest_0.21-0.7.3.jar.asc.md5
Uploading com/lihaoyi/utest_0.21/0.7.3/utest_0.21-0.7.3.jar.asc.sha1
Uploading com/lihaoyi/utest_0.21/0.7.3/utest_0.21-0.7.3-sources.jar.asc
Uploading com/lihaoyi/utest_0.21/0.7.3/utest_0.21-0.7.3-sources.jar.asc.md5
Uploading com/lihaoyi/utest_0.21/0.7.3/utest_0.21-0.7.3-sources.jar.asc.sha1
Uploading com/lihaoyi/utest_0.21/0.7.3/utest_0.21-0.7.3-javadoc.jar.asc
Uploading com/lihaoyi/utest_0.21/0.7.3/utest_0.21-0.7.3-javadoc.jar.asc.md5
Uploading com/lihaoyi/utest_0.21/0.7.3/utest_0.21-0.7.3-javadoc.jar.asc.sha1
Uploading com/lihaoyi/utest_0.21/0.7.3/utest_0.21-0.7.3.pom.asc
Uploading com/lihaoyi/utest_0.21/0.7.3/utest_0.21-0.7.3.pom.asc.md5
Uploading com/lihaoyi/utest_0.21/0.7.3/utest_0.21-0.7.3.pom.asc.sha1
```

**Comment by lihaoyi** [comment]
somehow the publish didn't actually go out; I just kicked it in the sonatype UI so hopefully it'll go out now

**Pull request merged**
