### PR TITLE
DO NOT MERGE - Topic/slowest

### PR DESCRIPTION
**Pull request by japgolly**
Hey @lihaoyi check this out. It adds an arg `--report-slowest` or `--report-slowest=n` which prints a report like:

```
[info] ...
[info] Tests: 20
[info] Passed: 20
[info] Failed: 0
[info] Slowest 5 tests:
[info]   #1: (52 ms) test.utest.FrameworkTests
[info]   #2: (11 ms) nesting.nesting
[info]   #3: (11 ms) helloWorld.helloWorld
[info]   #4: ( 6 ms) extractingResults.extractingResults
[info]   #5: ( 5 ms) nesting.runForking.runForking
```

Two problems:
1) `test -- --report--slowest` doesn't work. Seems to be SBT bug. `testOnly * -- --report--slowest` works.
2) I don't know how to get the full test name. You can see `nesting.nesting` in the results above? It should be `test.utest.FrameworkTests.nesting`. Do you know how to do that?

### CODE REVIEW

**Comment by japgolly** [comment]
@lihaoyi Are you able to provide any advice on those two problems I mentioned above? I'd like to fix and merge this.

**Comment by japgolly** [comment]
Ping @lihaoyi :)

**Comment by japgolly** [comment]
ping @lihaoyi as requested long ago :smile:

**Comment by lihaoyi** [comment]
Sorry I didn't find time to look at this...

The new renderer prints out times on a per-test and aggregated per-block or per-suite. That makes it pretty easy to skim the LHS of a test suite and see where all your time is going:

screenshot 2017-09-11 12 39 09

Does that already satisfy your use case of trying to find slow tests, or do you still want a reporting-style output that you showed here? Rather than baking the code into uTest itself, I feel like instead we should expose the test results to our `utest.runner.Framework#teardown` function or similar, which would make it trivial for you to implement this or all sorts of similar reports with a few lines of code in your codebase

**Comment by japgolly** [comment]
Yeah let's close this and see how we go

**Pull request closed without merging**
